application: datagroomer
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /static
  static_dir: dist
  secure: optional

- url: /files/.*
  script: py.files.app.app

- url: /.*
  script: py.frontend.app.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.git/.*)|
 (.*/node_modules/.*)|
 (.*/jspm_packages/.*)|
 (.*\.scss)|
 (.*\.md)|
 (build/.*)|
 )$
